# Generated by Django 4.1.4 on 2022-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_alter_category_options_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='catImages'),
            preserve_default=False,
        ),
    ]
