# Generated by Django 4.1.4 on 2022-12-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_category_img'),
        ('cartapp', '0002_alter_cartlist_cart_id_alter_cartlist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartapp.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeApp.products')),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='items',
            name='product',
        ),
        migrations.DeleteModel(
            name='cartList',
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
